name: "Npmrc Action"
description: "Create npmrc file"
author: "xxxxx@github.com"

inputs:
  github-token:
    description: 'Github token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup CI Git User
      shell: bash
      run: |
        git config --global user.name "miguelramos"
        git config --global user.email "miguel.ramos@websublime.dev"
        cat << EOF > "$HOME/.npmrc"
          //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          @websublime:registry=https://npm.pkg.github.com
        EOF
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

branding:
  icon: "shield"
  color: "blue"
