name: "PNPM Action"
description: "Install and cache pnpm"
author: "xxxxx@github.com"

inputs:
  cache-folder:
    description: 'Pnpm cache folder'
    required: false
    default: '.pnpm-store'
  npm-token:
    description: 'Npm token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install pnpm package manager
      shell: bash
      run: npm i pnpm@latest -g

    - name: Setup npmrc
      shell: bash
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" > .npmrc

    - name: Setup pnpm config
      shell: bash
      run: pnpm config set store-dir ${{ inputs.cache-folder }}

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ inputs.cache-folder }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

branding:
  icon: "tool"
  color: "purple"
