name: '[Action] Build Artifact'

on: pull_request

env:
  CI: true

jobs:
  prepare:
    name: Prepare Environment
    uses: ./.github/workflows/workflow-base.yml
    secrets: inherit
    steps:
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

