name: '[Action] Build Artifact'

on: pull_request

env:
  CI: true

jobs:
  prepare:
    uses: ./.github/workflows/workflow-base.yml
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
