name: Checks

on: pull_request

env:
  CI: true

run-name: Build ${{ github.ref_name }} by @${{ github.actor }}

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    secrets: inherit
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm package manager
        uses: ./.github/actions/pnpm
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
