name: Checks

on: pull_request

env:
  CI: true

run-name: Build ${{ github.event.pull_request.head.ref }} by @${{ github.actor }}

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    outputs:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: feature/reusable-actions

      - name: Install pnpm package manager
        id: install-pnpm
        uses: ./.github/actions/pnpm
        with:
          npm-token: ${{ needs.build.outputs.NPM_TOKEN }}

      - name: Install NodeJs
        id: install-node
        uses: ./.github/actions/node
