name: Checks

on:
  pull_request:
    branches-ignore:
      - 'changeset-release/**'
      - 'changeset-snapshot/**'

env:
  CI: true

run-name: '[Build]: ${{ github.event.pull_request.head.ref }} by @${{ github.actor }}'

jobs:
  build:
    name: Check Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: feature/reusable-actions

      - name: Install pnpm package manager
        id: install-pnpm
        uses: ./.github/actions/pnpm
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Install NodeJs
        id: install-node
        uses: ./.github/actions/node

      - name: Build Packages
        id: build-packages
        uses: ./.github/actions/build
