name: Lint Test

on: pull_request

jobs:
  build:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn bootstrap
      - name: Lint
        run: yarn lint

  dependabot:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
