name: Deploy Doc Website
on:
  push:
    branches:
      - master
      - main

env:
  CI: true

jobs:
  master-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Build Website
        run: yarn turbo run build
        env:
          NODE_ENV: 'production'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/playground/dist
          GIT_CONFIG_NAME: VitaminBot
          GIT_CONFIG_EMAIL: hello@websublime.dev
          COMMIT_MESSAGE: feat: website deploy
