name: Publish Packages

on:
  push:
    paths:
      - "packages/**"
    branches:
      - master
      - main
env:
  CI: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history
          # so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Test
        run: yarn test

      - name: Building packages
        run: yarn build
        env:
          NODE_ENV: 'production'

      - name: Setup CI Git User
        run: |
          git config --global user.name "miguelramos"
          git config --global user.email "miguel.marques.ramos@gmail.com"
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
            @websublime:registry=https://registry.npmjs.org
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish packages
        uses: changesets/action@master
        with:
          publish: yarn release
          title: "chore(release): version packages"
          commit: "chore(release): version packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
