name: Release

on:
  push:
    branches:
      - main

env:
  CI: true

run-name: '[Release]: Release for ${{ github.ref_name }}'

jobs:
  release-build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm package manager
        id: install-pnpm
        uses: ./.github/actions/pnpm
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Install NodeJs
        id: install-node
        uses: ./.github/actions/node

      - name: Build Packages
        id: build-packages
        uses: ./.github/actions/build

      - name: Setup CI Git User
        id: setup-ci-git-user
        uses: ./.github/actions/npmrc
        with:
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Create Snapshot
        uses: changesets/action@v1.4.5
        with:
          setupGitUser: false
          #version: pnpm snapshot:version
          publish: pnpm release
          title: "chore(release): Stable Release"
          commit: "chore(release): deploy stable release"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
