name: Build and Deploy Feature artifacts

on:
  push:
    branches-ignore:
      - $default-branch
      - 'main'
      - 'changeset-set-release/**'

env:
  CI: true
  NODE_ENV: "develop"
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  build:
    name: Snapshot Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm package manager
        run: npm i pnpm@latest -g

      - name: Setup CI Git User
        run: |
          git config --global user.name "miguelramos"
          git config --global user.email "miguel.ramos@websublime.dev"
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
            @websublime:registry=https://npm.pkg.github.com
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create Snapshot
        uses: changesets/action@v1.4.5
        with:
          version: pnpm snapshot:version
          publish: pnpm snapshot:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
