name: Unit Test

on: pull_request

env:
  CI: true

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Test
        run: yarn test

      - name: Test build lib
        run: yarn build:lib
        env:
          NODE_ENV: 'production'

      - name: Test build site
        run: yarn build:play

  dependabot:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
