name: '[Workflow] Build'

jobs:
  checkout-repo:
    name: Build bundle
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
